# This file was generated by the {rix} R package v0.12.4 on 2024-12-01
# with following call:
# >rix(r_ver = "581d7e4d23b91daf2afa0005a5d3d01d6a8884fe",
#  > r_pkgs = c("ggplot2"),
#  > system_pkgs = NULL,
#  > git_pkgs = NULL,
#  > ide = "code",
#  > project_path = "~/Desktop/rix-mytutorial/",
#  > overwrite = TRUE,
#  > print = TRUE,
#  > shell_hook = NULL)
# It uses nixpkgs' revision 581d7e4d23b91daf2afa0005a5d3d01d6a8884fe for reproducibility purposes
# which will install R version latest.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/581d7e4d23b91daf2afa0005a5d3d01d6a8884fe.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      ggplot2
      languageserver;
  };
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [  rpkgs  system_packages   ];
  
}
